Решена задача StepSliderV1
js-tasks-ru/jsbasic-20240219_shadrov-vladimir pull request #8
Opened 2024-03-20 10:06 UTC by VladimirShadrov

Добавил решение задачи StepSlider, часть 1

2024-03-20 10:07 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-03-20 15:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-03-21 09:50 UTC, koalex requested changes
Исправить замечание в **7-4**

2024-03-21 09:50 UTC, koalex commented on 7-module/4-task/index.js
> +    this.value = Math.round(left / this.elem.offsetWidth * this.clusters);
Когда элемент ещё не отрисован, то ширина this.elem.offsetWidth равна 0
получается left = 0, this.elem.offsetWidth = 0
0 / 0 будет NaN
Добавьте проверку:
```
if (this.elem.offsetWidth) {
    this.value = Math.round(left / this.elem.offsetWidth * this.clusters);
}
```

2024-03-21 16:34 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-03-22 10:48 UTC, koalex approved these changes

2024-03-22 10:48 UTC, merged